language: python
python:
  - "2.6"
  - "2.7"
services:
  - couchdb
sudo: false
before_script:
    - pip install -U pip
    - pip --version
    - pip install -U coveralls unittest2 nose nose-testconfig mock
script:
  - python setup.py install
  - python setup.py nosetests
after_success:
  - coveralls
